name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      - name: Run affected tests
        run: npx nx affected -t lint test build --configuration=ci

      - name: Retry flaky tests
        if: ${{ always() }}
        run: |
          echo "Checking for flaky tests..."
          # Simulated retry logic. Replace with your real test reporting
          if [ -f jest-failures.json ]; then
            failed_projects=$(jq -r '.testResults[] | select(.status=="failed") | .name' jest-failures.json | xargs)
            for proj in $failed_projects; do
              echo "Re-running flaky test for $proj"
              npx nx test $proj --configuration=ci
            done
          fi
